### ISSUE TITLE
Update EVO to work with restructure of data objects

### ISSUE THREAD

**Issue by leshghi** [amgrubb/BloomingLeaf#447]
As the structure of our data changes, EVO will need to be updated in order to properly access the parameters needed. This will happen primarily in the evoObjects.js file. If the structure of the analysisResult data changes as well, there will be additional updating needed. This will mostly just mean changing lines like model.getIntentionByNodeID() to cell.get('intention'), etc.

**Comment by Manarnz** [comment]
Methods malfunctioning in class EVO:
- [x] refresh() → analysisResult is not defined
- [x] colorIntentionsModeling() → The issue is a model.getIntentionByID, which is related to issue #484
- [x] colorIntentionsAnalysis() → The issue is a model.getIntentionByID, which is related to issue #484. Additionally, count in line 350 is not defined
- [x] changeIntentionsText() → The issue is a model.getIntentionByID, which is related to issue #484.

**Comment by Manarnz** [comment]
Issues related to EVO:
- [x] #349 
- [x] #280 
- [ ] #221

**Comment by Manarnz** [comment]
TODOs dependent on EVO:
- [ ] backendComm.js in line 24 update getAllNextStates()
- [ ] evoObjects.js in class EVO there is TODO: docstring
